### ISSUE TITLE
Unvalid ASSETS_URL link

### ISSUE THREAD

**Issue by Cardistymo** [MinecraftCapes/BLCResizer#1]
There is a comment "change this", but how do I get a valid link?

**Comment by james090500** [comment]
Either, open up BadLion and you will see title of the Minecraft window will be something like - `v3.9.0.1-4a32816-PRODUCTION3`

Or go in to the BadLion Discord and search for images people posted which is what I do. 

I am yet to find a way to get this version automatically. 

eg;
![image](https://user-images.githubusercontent.com/20372645/172343955-93cfd06c-0bbc-4588-b798-8f4f1f3691c2.png)

**Comment by Cardistymo** [comment]
thanks, is there any way to identify which number is which cape?

**Comment by Cardistymo** [comment]
Ok, nice application!
